### ISSUE TITLE
Possible CORS issue with Elasticsearch

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/ember-fedora-adapter#13]
Elasticsearch config specifies `localhost:4200` (https://github.com/OA-PASS/ember-fedora-adapter/blob/master/.elasticsearch.yml#L3) as the only allowed origin. Need to make sure this is synced with where the Ember app is deployed

**Comment by markpatton** [comment]
Yes. There is a custom elasticsearch config that is used just for this repository. Production doesn't have to worry about cors.

**Comment by jabrah** [comment]
Just need to make sure to run tests and do testing on the right port, then.
