### ISSUE TITLE
Implement findAll with Elasticsearch

### ISSUE THREAD

**Issue by markpatton** [OA-PASS/ember-fedora-adapter#9]
The findAll command will work poorly with large containers. It relies on the Fedora include container Prefer header. Using Elasticsearch makes more sense. The findAll message does not support paging, so the query should be restricted to some reasonable size.

**Comment by birkland** [comment]
Maybe just don't implement it in elastic and leave it as-is?  Are there any use cases (or usages) for findAll in the ember app?

**Comment by markpatton** [comment]
The current decision is that this is lower priority. I just made an issue so we don't forget.

**Comment by markpatton** [comment]
Done earlier.
